cargo-features = ["edition2024"]

[package]
name = "frontend"
version = "0.0.1"
edition = "2024"

[dependencies]
yew = {version = "0.21", features = ["csr"] }
yew-router = "0.18.0"
wasm-bindgen = "0.2.95"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
