cargo-features = ["edition2024"]
 
[package]
name =		"backend"
version =	"0.0.1"
edition =	"2024"

[dependencies]
uuid = { version = "1.2", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
